spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/platform_auth_sample
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update